### ISSUE TITLE
Searchplus - Tab workcat: Filter feature_id not working

### ISSUE THREAD

**Issue by daviderill** [Giswater/giswater_qgis_plugin#343]
A new view will be created that performs same query as it is in Python code
Call that view in Python

**Comment by bbrzepka** [comment]
View is called v_ui_workcat_x_feature.
 It shows all features that has value of workcat_id or workcat_id_end. If the user wants to open a form of a feature with different value of state or exploitation than he has choosen in selector the show info message should appear saying that feature is not visible on the map because of selectors configuration.

**Comment by daviderill** [comment]
@nestorip How is the situation with this issue?
